apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestlistapplication
  labels:
    app: guestlistapplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestlistapplication
  template:
    metadata:
      labels:
        app: guestlistapplication
    spec:
      containers:
        - name: guestlistapplication
          image: vijaypsundefined53/guestlistapplication:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9201
              protocol: TCP