apiVersion: v1
kind: Service
metadata:
  name: guestlistapplication-service
spec:
  selector:
    app: guestlistapplication
  ports:
    - protocol: TCP
      port: 9201
      targetPort: 9201
      name: http
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.0.2.127
